services:
  db:
    build:
      context: ./db
    container_name: CommverseDB
    image: postgres
    restart: always
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env

volumes:
  postgres: