services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: CommverseDB
    image: postgres
    restart: always
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: CommverseBackend
    depends_on:
      - db
    ports: 
      - "9090:9090"

volumes:
  postgres: